# Sniperkit-Bot
# - Status: analyzed

apiVersion: v1
kind: Service
metadata:
  labels:
    service: master
  name: master
  namespace: gleam
spec:
  ports:
  - name: gleam-web-ui
    port: 45326
    protocol: TCP
  clusterIP: None
  selector:
    service: master